"""Deterministic repository contracts for the v5 plan-craft skill."""

from __future__ import annotations

from pathlib import Path
import unittest

from build_plugin_assets_test_support import (
    GENERATED_MARKDOWN_WARNING,
    IsolatedRepositorySupport,
    REPOSITORY_ROOT,
    generated_skill_path,
    shared_skill_path,
)


PLAN_CRAFT_V5_SKILL = "plan-craft-v5"
PLAN_CRAFT_V5_CODEX_METADATA = Path(
    "plugins/codex/skills/plan-craft-v5/agents/openai.yaml"
)
PLAN_CRAFT_V5_EXPECTED_PATHS = (
    Path("shared/skill/plan-craft-v5/SKILL.md"),
    Path("plugins/claude/skills/plan-craft-v5/SKILL.md"),
    Path("plugins/codex/skills/plan-craft-v5/SKILL.md"),
    PLAN_CRAFT_V5_CODEX_METADATA,
)


class PlanCraftV5SkillContractsTest(IsolatedRepositorySupport, unittest.TestCase):
    def test_plan_craft_v5_has_exact_source_and_runtime_path_inventory(self) -> None:
        """Keep the temporary v5 skill's authored and generated surface bounded."""
        existing = {
            path.relative_to(REPOSITORY_ROOT)
            for root in (
                REPOSITORY_ROOT / "shared/skill/plan-craft-v5",
                REPOSITORY_ROOT / "plugins/claude/skills/plan-craft-v5",
                REPOSITORY_ROOT / "plugins/codex/skills/plan-craft-v5",
            )
            for path in root.rglob("*")
            if path.is_file()
        }
        self.assertEqual(set(PLAN_CRAFT_V5_EXPECTED_PATHS), existing)

    def test_plan_craft_v5_is_explicit_only_on_both_platforms(self) -> None:
        """Require explicit invocation metadata without changing the v4 skill."""
        source = (REPOSITORY_ROOT / shared_skill_path(PLAN_CRAFT_V5_SKILL)).read_text(
            encoding="utf-8"
        )
        claude = (REPOSITORY_ROOT / generated_skill_path("claude", PLAN_CRAFT_V5_SKILL)).read_text(
            encoding="utf-8"
        )
        codex = (REPOSITORY_ROOT / generated_skill_path("codex", PLAN_CRAFT_V5_SKILL)).read_text(
            encoding="utf-8"
        )
        self.assertIn("disable-model-invocation: true", source)
        self.assertIn("disable-model-invocation: true", claude)
        self.assertNotIn("disable-model-invocation: true", codex.split("---", 2)[1])
        self.assertTrue(codex.startswith("---\nname: plan-craft-v5\n"))
        self.assertIn(GENERATED_MARKDOWN_WARNING, codex)
        self.assertNotIn("<!-- claude-only", claude)
        self.assertNotIn("<!-- codex-only", codex)
        self.assertNotIn("<!-- claude-only", codex)

    def test_build_replaces_stale_plan_craft_v5_outputs_with_source_derived_bytes(self) -> None:
        """Replace stale copies and match the repository's Claude/Codex generated bytes exactly."""
        with self._temporary_repository() as root:
            expected = self._seed_real_skill_source(root, PLAN_CRAFT_V5_SKILL)
            result = self._run(root)
            self.assertEqual(0, result.returncode, result)
            for platform in ("claude", "codex"):
                output = (root / generated_skill_path(platform, PLAN_CRAFT_V5_SKILL)).read_bytes()
                self.assertEqual(expected[platform], output)

    def test_plan_craft_v5_codex_metadata_has_scalar_interface(self) -> None:
        """Keep Codex interface metadata scalar and explicit-only."""
        metadata = (REPOSITORY_ROOT / PLAN_CRAFT_V5_CODEX_METADATA).read_text(
            encoding="utf-8"
        )
        self.assertEqual(
            """interface:
  display_name: "Plan Craft v5"
  short_description: "Draft a free-form plan without starting implementation"
  default_prompt: "Use $plan-craft-v5 to draft or refine a free-form planning artifact without implementing, delegating, or advancing to a next stage."
policy:
  allow_implicit_invocation: false
""",
            metadata,
        )


if __name__ == "__main__":
    unittest.main()
