"""Deterministic repository contracts for the v5 review-loop skill."""

from __future__ import annotations

from pathlib import Path
import unittest

from build_plugin_assets_test_support import (
    GENERATED_MARKDOWN_WARNING,
    IsolatedRepositorySupport,
    REPOSITORY_ROOT,
    generated_skill_path,
    shared_skill_path,
)


REVIEW_LOOP_SKILL = "review-loop"
REVIEW_LOOP_CODEX_METADATA = Path(
    "plugins/codex/skills/review-loop/agents/openai.yaml"
)
REVIEW_LOOP_EXPECTED_PATHS = (
    Path("shared/skill/review-loop/SKILL.md"),
    Path("plugins/claude/skills/review-loop/SKILL.md"),
    Path("plugins/codex/skills/review-loop/SKILL.md"),
    REVIEW_LOOP_CODEX_METADATA,
)


class ReviewLoopSkillContractsTest(IsolatedRepositorySupport, unittest.TestCase):
    def test_review_loop_has_exact_source_and_runtime_path_inventory(self) -> None:
        """Keep the new skill's authored and generated surface bounded to four files."""
        existing = {
            path.relative_to(REPOSITORY_ROOT)
            for path in (
                REPOSITORY_ROOT / "shared/skill/review-loop"
            ).rglob("*")
            if path.is_file()
        } | {
            path.relative_to(REPOSITORY_ROOT)
            for platform in ("claude", "codex")
            for path in (
                REPOSITORY_ROOT / f"plugins/{platform}/skills/review-loop"
            ).rglob("*")
            if path.is_file()
        }
        self.assertEqual(set(REVIEW_LOOP_EXPECTED_PATHS), existing)

    def test_review_loop_markdown_omits_implicit_disable_and_platform_markers(self) -> None:
        """Ensure shared and generated Markdown omit Claude's implicit-disable flag and platform markers."""
        source = (REPOSITORY_ROOT / shared_skill_path(REVIEW_LOOP_SKILL)).read_text(
            encoding="utf-8"
        )
        claude = (REPOSITORY_ROOT / generated_skill_path("claude", REVIEW_LOOP_SKILL)).read_text(
            encoding="utf-8"
        )
        codex = (REPOSITORY_ROOT / generated_skill_path("codex", REVIEW_LOOP_SKILL)).read_text(
            encoding="utf-8"
        )
        self.assertNotIn("disable-model-invocation", source)
        self.assertTrue(claude.startswith("---\nname: review-loop\n"))
        self.assertNotIn("disable-model-invocation", claude)
        self.assertTrue(codex.startswith("---\nname: review-loop\n"))
        self.assertIn(GENERATED_MARKDOWN_WARNING, codex)
        self.assertNotIn("disable-model-invocation", codex)

    def test_review_loop_codex_metadata_is_scalar_and_source_aligned(self) -> None:
        """Keep Codex interface metadata scalar and aligned with the skill name."""
        metadata = (REPOSITORY_ROOT / REVIEW_LOOP_CODEX_METADATA).read_text(
            encoding="utf-8"
        )
        self.assertEqual(
            """interface:
  display_name: "Review Loop"
  short_description: "Review an artifact with bounded rounds and final trim"
  default_prompt: "Use $review-loop to review an immutable artifact snapshot and return findings, termination, and caller-owned acceptance evidence."
policy:
  allow_implicit_invocation: true
""",
            metadata,
        )

    def test_build_replaces_stale_review_loop_outputs_with_source_derived_bytes(self) -> None:
        """Replace stale copies and match the repository's Claude/Codex generated bytes exactly."""
        with self._temporary_repository() as root:
            expected = self._seed_real_skill_source(root, REVIEW_LOOP_SKILL)
            result = self._run(root)
            self.assertEqual(0, result.returncode, result)
            for platform in ("claude", "codex"):
                output = (root / generated_skill_path(platform, REVIEW_LOOP_SKILL)).read_bytes()
                self.assertEqual(expected[platform], output)


if __name__ == "__main__":
    unittest.main()
